### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dconroy** [mtlynch/ingredient-phrase-tagger#60]
Thanks for this repo. Do you have a rough guess of what it would take to support python 3?

**Comment by mtlynch** [comment]
It shouldn't be too hard. There's not that much code overall, and even of what's there, not much is Python2-specific. I haven't looked closely, but I'd estimate 2-8 hours of work for a developer who's comfortable in Python3.

**Comment by dconroy** [comment]
thanks for quick reply

**Comment by dgrant** [comment]
@mtlynch Hey, would you support a PR that moves to Python 3 and drops Python 2 support completely?

**Comment by mtlynch** [comment]
@dgrant - Yeah, that would be great!

**Comment by wcedmisten** [comment]
@dgrant @mtlynch I put up a draft PR for this: https://github.com/mtlynch/ingredient-phrase-tagger/pull/62.

This might be helpful as a reference, because the changes seem to break training the model in the docker image for me. I'm not quite sure why this is happening, but I'll keep looking.
