### ISSUE TITLE
Discrepancy in testing_output with golden master

### ISSUE THREAD

**Issue by dgrant** [mtlynch/ingredient-phrase-tagger#66]
Hi @mtlynch I'm getting some discrepancies between testing_output produced locally and golden master

I'm getting stuff like this:

```
*** 15377,15382 ****
  or	I5	L16	NoCAP	NoPAREN	OTHER	I-COMMENT
  frozen	I6	L16	NoCAP	NoPAREN	OTHER	I-COMMENT
! fava	I7	L16	NoCAP	NoPAREN	B-NAME	B-NAME
! beans	I8	L16	NoCAP	NoPAREN	I-NAME	I-NAME
  ,	I9	L16	NoCAP	NoPAREN	B-COMMENT	B-COMMENT
  or	I10	L16	NoCAP	NoPAREN	OTHER	I-COMMENT
--- 15377,15382 ----
  or	I5	L16	NoCAP	NoPAREN	OTHER	I-COMMENT
  frozen	I6	L16	NoCAP	NoPAREN	OTHER	I-COMMENT
! fava	I7	L16	NoCAP	NoPAREN	B-NAME	I-COMMENT
! beans	I8	L16	NoCAP	NoPAREN	I-NAME	B-NAME
  ,	I9	L16	NoCAP	NoPAREN	B-COMMENT	B-COMMENT
  or	I10	L16	NoCAP	NoPAREN	OTHER	I-COMMENT
```

which is exactly what you were also getting as described in [your blog post](https://mtlynch.io/resurrecting-2/).

I'm using CRF++ 0.58, compiled locally, which is probably the same version you're using. So maybe something else in CRF++ besides the number of threads is causing the issue.

**Comment by mtlynch** [comment]
I'm guessing that compiling CRF++ in different environments yields slightly different behavior. You can work around this with `docker_build` which uses the Docker image that has a pre-compiled version of CRF++, so it should have consistent behavior across environments.

Unfortunately, the difference in behavior across environments is a CRF++ bug, so there's not much we can do from the ingredient-phrase-tagger side.
